#!/bin/bash

echo
echo " --- Integrations tests:"
echo

shellcheck -e SC1083 -e SC1089 integration_test/* || exit
shellcheck src/* || exit

echo "SHELLCHECK: OK"


echo
echo "BATS:"
echo
bats integration_test/*
